global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${ALERTMANAGER_EMAIL}'
  smtp_auth_username: '${ALERTMANAGER_EMAIL}'
  smtp_auth_password: '${ALERTMANAGER_PASSWORD}'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-alerts'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'your-email@gmail.com'
        subject: 'Portfolio Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          {{ end }}